module.exports = {
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  parser: "@typescript-eslint/parser",
  plugins: ["import", "@typescript-eslint"],
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/typescript",
    "plugin:promise/recommended",
    "prettier",
  ],
  rules: {
    curly: 1,
    "import/no-default-export": 1,
    "import/order": 2,
    "no-await-in-loop": 2,
    "no-console": 1,
    "no-duplicate-imports": 2,
    "no-else-return": 2,
    "no-new-object": 2,
    "no-new-func": 2,
    "no-return-assign": 2,
    "no-return-await": 1,
    "no-self-compare": 2,
    "no-template-curly-in-string": 2,
    "no-useless-return": 2,
    "@typescript-eslint/consistent-type-imports": [
      2,
      { prefer: "type-imports", fixStyle: "inline-type-imports" },
    ],
    "@typescript-eslint/strict-boolean-expressions": 2,
  },
};
